title: 'liulch.github.io'
description: "Licheng Liu's Personal Website."
baseurl: ""
url: "https://liulch.github.io"

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
# theme: jekyll-theme-console

header_pages:
  - index.md
  - peter.md
  - about.md
  - contact.md

style: light 

footer: '<a href="https://scholar.google.com/citations?user=xbcmrRAAAAAJ">Google Scholar</a> <a href="https://github.com/liulch">GitHub</a> <a href="https://twitter.com/liulch16">Twitter</a>'

